add licese data
kaiyuanshe/Open-Source-License-filter pull request #2
Opened 2022-12-22 09:30 UTC by luojiyin1987

2022-12-22 09:31 UTC, luojiyin1987 commented
还要补充 对应 license 的访问 url

2022-12-22 14:27 UTC, TechQuery requested changes

2022-12-22 14:27 UTC, TechQuery commented on source/data.ts
> +
Git hooks 格式化脚本应该没有执行

2022-12-23 14:28 UTC, TechQuery approved these changes

2022-12-23 14:29 UTC, merged